templateDir:
  templates
files:
  AUTHORS.md:
    {}
  openapi_server/controllers/CDBusDraculaService.py:
    folder: .
  openapi_server/controllers/measurement_channel_controller.py:
    folder: .
  openapi_server/controllers/control_channel_controller.py:
    folder: .
