# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse400(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, detail=None, status=None, title=None, type=None):  # noqa: E501
        """InlineResponse400 - a model defined in OpenAPI

        :param detail: The detail of this InlineResponse400.  # noqa: E501
        :type detail: str
        :param status: The status of this InlineResponse400.  # noqa: E501
        :type status: float
        :param title: The title of this InlineResponse400.  # noqa: E501
        :type title: str
        :param type: The type of this InlineResponse400.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'detail': str,
            'status': float,
            'title': str,
            'type': str
        }

        self.attribute_map = {
            'detail': 'detail',
            'status': 'status',
            'title': 'title',
            'type': 'type'
        }

        self._detail = detail
        self._status = status
        self._title = title
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse400':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_400 of this InlineResponse400.  # noqa: E501
        :rtype: InlineResponse400
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detail(self):
        """Gets the detail of this InlineResponse400.

        A description of the problem with the request  # noqa: E501

        :return: The detail of this InlineResponse400.
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this InlineResponse400.

        A description of the problem with the request  # noqa: E501

        :param detail: The detail of this InlineResponse400.
        :type detail: str
        """
        if detail is None:
            raise ValueError("Invalid value for `detail`, must not be `None`")  # noqa: E501

        self._detail = detail

    @property
    def status(self):
        """Gets the status of this InlineResponse400.

        The number of the HTTP error code  # noqa: E501

        :return: The status of this InlineResponse400.
        :rtype: float
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse400.

        The number of the HTTP error code  # noqa: E501

        :param status: The status of this InlineResponse400.
        :type status: float
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def title(self):
        """Gets the title of this InlineResponse400.

        The title of the error indicated by the status  # noqa: E501

        :return: The title of this InlineResponse400.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this InlineResponse400.

        The title of the error indicated by the status  # noqa: E501

        :param title: The title of this InlineResponse400.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def type(self):
        """Gets the type of this InlineResponse400.

        Additional error information if available describing the type of error  # noqa: E501

        :return: The type of this InlineResponse400.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InlineResponse400.

        Additional error information if available describing the type of error  # noqa: E501

        :param type: The type of this InlineResponse400.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type
