/*
 * Analyzer and HUB API
 * The definition of the software interface between analyzers and the HUB.  The interface will be implemented as a RESTful interface with all server endpoints hosted on the Analyzer.  The following requirements will be met by all interfaces:  1. All data passed back from server shall be in JSON format. 2. All query parameters and JSON data properties shall be named using snake case and be all lower case. 4. All data types that describe a measurement value shall end with an underscore followed by the unit of that physical value.  i.e. motor_current_ma.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.MeasurementResult;

/**
 * InlineResponse2001
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-09-01T10:02:09.757-04:00[America/Nassau]")
public class InlineResponse2001 {
  public static final String SERIALIZED_NAME_MEASUREMENT_RESULTS = "measurement_results";
  @SerializedName(SERIALIZED_NAME_MEASUREMENT_RESULTS)
  private List<MeasurementResult> measurementResults = new ArrayList<MeasurementResult>();


  public InlineResponse2001 measurementResults(List<MeasurementResult> measurementResults) {
    
    this.measurementResults = measurementResults;
    return this;
  }

  public InlineResponse2001 addMeasurementResultsItem(MeasurementResult measurementResultsItem) {
    this.measurementResults.add(measurementResultsItem);
    return this;
  }

   /**
   * An array of measurement result objects that were taken in between the times sent in the request.  If there are no historical results to report, this will return as an empty array
   * @return measurementResults
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "An array of measurement result objects that were taken in between the times sent in the request.  If there are no historical results to report, this will return as an empty array")

  public List<MeasurementResult> getMeasurementResults() {
    return measurementResults;
  }


  public void setMeasurementResults(List<MeasurementResult> measurementResults) {
    this.measurementResults = measurementResults;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.measurementResults, inlineResponse2001.measurementResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(measurementResults);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    sb.append("    measurementResults: ").append(toIndentedString(measurementResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

