# coding: utf-8

"""
    Analyzer and HUB API

    The definition of the software interface between analyzers and the HUB.  The interface will be implemented as a RESTful interface with all server endpoints hosted on the Analyzer.  The following requirements will be met by all interfaces:  1. All data passed back from server shall be in JSON format. 2. All query parameters and JSON data properties shall be named using snake case and be all lower case. 4. All data types that describe a measurement value shall end with an underscore followed by the unit of that physical value.  i.e. motor_current_ma.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.control_channel_api import ControlChannelApi  # noqa: E501
from openapi_client.rest import ApiException


class TestControlChannelApi(unittest.TestCase):
    """ControlChannelApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.control_channel_api.ControlChannelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_control_light_blink_put(self):
        """Test case for control_light_blink_put

        """
        pass

    def test_control_power_off_put(self):
        """Test case for control_power_off_put

        """
        pass

    def test_control_power_reboot_put(self):
        """Test case for control_power_reboot_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
