# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AnalyzerType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    SPE = "SPE"
    LTF = "LTF"
    MOL = "MOL"

    def __init__(self):
        """AnalyzerType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AnalyzerType':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The analyzer_type of this AnalyzerType.
        """
        return util.deserialize_model(dikt, cls)
