# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, script: str=None):
        """InlineObject - a model defined in OpenAPI

        :param script: The script of this InlineObject.
        """
        self.openapi_types = {
            'script': str
        }

        self.attribute_map = {
            'script': 'script'
        }

        self._script = script

    @classmethod
    def from_dict(cls, dikt: dict) -> 'InlineObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The inline_object of this InlineObject.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def script(self):
        """Gets the script of this InlineObject.

        This string will contain a script that the analyzer will consume and begin the execution of

        :return: The script of this InlineObject.
        :rtype: str
        """
        return self._script

    @script.setter
    def script(self, script):
        """Sets the script of this InlineObject.

        This string will contain a script that the analyzer will consume and begin the execution of

        :param script: The script of this InlineObject.
        :type script: str
        """
        if script is None:
            raise ValueError("Invalid value for `script`, must not be `None`")

        self._script = script
