# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class MeasurementStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    INITIALIZING = "Initializing"
    RUNNING = "Running"
    ABORTED = "Aborted"
    STOPPING = "Stopping"
    COMPLETE = "Complete"

    def __init__(self):
        """MeasurementStatus - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'MeasurementStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The measurement_status of this MeasurementStatus.
        """
        return util.deserialize_model(dikt, cls)
