server:
  port: 8074
spring:
  cloud:
    loadbalancer:
      enabled: false
    zookeeper:
      connect-string: localhost:2181
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092
      group-id: ic-platform
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
test:
  topic: embedded-test-topic