/*
 * Analyzer and HUB API
 * The definition of the software interface between analyzers and the HUB.  The interface will be implemented as a RESTful interface with all server endpoints hosted on the Analyzer.  The following requirements will be met by all interfaces:  1. All data passed back from server shall be in JSON format. 2. All query parameters and JSON data properties shall be named using snake case and be all lower case. 4. All data types that describe a measurement value shall end with an underscore followed by the unit of that physical value.  i.e. motor_current_ma.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ResponseMeasurementResult
 */
public class ResponseMeasurementResultTest {
    private final ResponseMeasurementResult model = new ResponseMeasurementResult();

    /**
     * Model tests for ResponseMeasurementResult
     */
    @Test
    public void testResponseMeasurementResult() {
        // TODO: test ResponseMeasurementResult
    }

    /**
     * Test the property 'consumableName'
     */
    @Test
    public void consumableNameTest() {
        // TODO: test consumableName
    }

    /**
     * Test the property 'startDatetime'
     */
    @Test
    public void startDatetimeTest() {
        // TODO: test startDatetime
    }

    /**
     * Test the property 'endDatetime'
     */
    @Test
    public void endDatetimeTest() {
        // TODO: test endDatetime
    }

    /**
     * Test the property 'durationSec'
     */
    @Test
    public void durationSecTest() {
        // TODO: test durationSec
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'testResults'
     */
    @Test
    public void testResultsTest() {
        // TODO: test testResults
    }

}
